-- aswt_txn_view source

CREATE OR REPLACE VIEW aswt_txn_view
AS (
        (
                 SELECT aswt_switch_txn_offline.settle_flag,
                    aswt_switch_txn_offline.txn_issuer,
                    aswt_switch_txn_offline.txn_fwd_inst_1,
                    aswt_switch_txn_offline.txn_fwd_inst_2,
                    aswt_switch_txn_offline.txn_auth_source,
                    aswt_switch_txn_offline.txn_channel,
                    aswt_switch_txn_offline.txn_type,
                    aswt_switch_txn_offline.txn_code,
                    aswt_switch_txn_offline.txn_date,
                    aswt_switch_txn_offline.txn_time,
                    aswt_switch_txn_offline.fp_masked,
                    aswt_switch_txn_offline.fp_type,
                    aswt_switch_txn_offline.int_mti,
                    aswt_switch_txn_offline.int_ref_no,
                    aswt_switch_txn_offline.txn_batch_no,
                    aswt_switch_txn_offline.txn_batch_status,
                    aswt_switch_txn_offline.drcr,
                    aswt_switch_txn_offline.fp_form_factor,
                    aswt_switch_txn_offline.int_seq_no,
                    aswt_switch_txn_offline.int_rc,
                    aswt_switch_txn_offline.scheme,
                    aswt_switch_txn_offline.int_rrn,
                    aswt_switch_txn_offline.int_proc_code,
                    aswt_switch_txn_offline.int_amt,
                    aswt_switch_txn_offline.int_adj_amt1,
                    aswt_switch_txn_offline.int_adj_amt2,
                    aswt_switch_txn_offline.int_txn_fees1,
                    aswt_switch_txn_offline.int_txn_fees2,
                    aswt_switch_txn_offline.int_pos_entry_mode,
                    aswt_switch_txn_offline.int_void_flag,
                    aswt_switch_txn_offline.mti,
                    aswt_switch_txn_offline.f002,
                    aswt_switch_txn_offline.f003,
                    aswt_switch_txn_offline.f004,
                    aswt_switch_txn_offline.f005,
                    aswt_switch_txn_offline.f006,
                    aswt_switch_txn_offline.f007,
                    aswt_switch_txn_offline.f008,
                    aswt_switch_txn_offline.f009,
                    aswt_switch_txn_offline.f010,
                    aswt_switch_txn_offline.f011,
                    aswt_switch_txn_offline.f012,
                    aswt_switch_txn_offline.f013,
                    aswt_switch_txn_offline.f014,
                    aswt_switch_txn_offline.f015,
                    aswt_switch_txn_offline.f016,
                    aswt_switch_txn_offline.f017,
                    aswt_switch_txn_offline.f018,
                    aswt_switch_txn_offline.f019,
                    aswt_switch_txn_offline.f020,
                    aswt_switch_txn_offline.f021,
                    aswt_switch_txn_offline.f022,
                    aswt_switch_txn_offline.f023,
                    aswt_switch_txn_offline.f024,
                    aswt_switch_txn_offline.f025,
                    aswt_switch_txn_offline.f026,
                    aswt_switch_txn_offline.f027,
                    aswt_switch_txn_offline.f028,
                    aswt_switch_txn_offline.f029,
                    aswt_switch_txn_offline.f030,
                    aswt_switch_txn_offline.f031,
                    aswt_switch_txn_offline.f032,
                    aswt_switch_txn_offline.f033,
                    aswt_switch_txn_offline.f034,
                    aswt_switch_txn_offline.f035,
                    aswt_switch_txn_offline.f036,
                    aswt_switch_txn_offline.f037,
                    aswt_switch_txn_offline.f038,
                    aswt_switch_txn_offline.f039,
                    aswt_switch_txn_offline.f040,
                    aswt_switch_txn_offline.f041,
                    aswt_switch_txn_offline.f042,
                    aswt_switch_txn_offline.f043,
                    aswt_switch_txn_offline.f044,
                    aswt_switch_txn_offline.f045,
                    aswt_switch_txn_offline.f046,
                    aswt_switch_txn_offline.f047,
                    aswt_switch_txn_offline.f048,
                    aswt_switch_txn_offline.f049,
                    aswt_switch_txn_offline.f050,
                    aswt_switch_txn_offline.f051,
                    aswt_switch_txn_offline.f052,
                    aswt_switch_txn_offline.f053,
                    aswt_switch_txn_offline.f054,
                    aswt_switch_txn_offline.f055,
                    aswt_switch_txn_offline.f056,
                    aswt_switch_txn_offline.f057,
                    aswt_switch_txn_offline.f058,
                    aswt_switch_txn_offline.f059,
                    aswt_switch_txn_offline.f060,
                    aswt_switch_txn_offline.f061,
                    aswt_switch_txn_offline.f062,
                    aswt_switch_txn_offline.f063,
                    aswt_switch_txn_offline.f064,
                    aswt_switch_txn_offline.f065,
                    aswt_switch_txn_offline.f066,
                    aswt_switch_txn_offline.f067,
                    aswt_switch_txn_offline.f068,
                    aswt_switch_txn_offline.f069,
                    aswt_switch_txn_offline.f070,
                    aswt_switch_txn_offline.f071,
                    aswt_switch_txn_offline.f072,
                    aswt_switch_txn_offline.f073,
                    aswt_switch_txn_offline.f074,
                    aswt_switch_txn_offline.f075,
                    aswt_switch_txn_offline.f076,
                    aswt_switch_txn_offline.f077,
                    aswt_switch_txn_offline.f078,
                    aswt_switch_txn_offline.f079,
                    aswt_switch_txn_offline.f080,
                    aswt_switch_txn_offline.f081,
                    aswt_switch_txn_offline.f082,
                    aswt_switch_txn_offline.f083,
                    aswt_switch_txn_offline.f084,
                    aswt_switch_txn_offline.f085,
                    aswt_switch_txn_offline.f086,
                    aswt_switch_txn_offline.f087,
                    aswt_switch_txn_offline.f088,
                    aswt_switch_txn_offline.f089,
                    aswt_switch_txn_offline.f090,
                    aswt_switch_txn_offline.f091,
                    aswt_switch_txn_offline.f092,
                    aswt_switch_txn_offline.f093,
                    aswt_switch_txn_offline.f094,
                    aswt_switch_txn_offline.f095,
                    aswt_switch_txn_offline.f096,
                    aswt_switch_txn_offline.f097,
                    aswt_switch_txn_offline.f098,
                    aswt_switch_txn_offline.f099,
                    aswt_switch_txn_offline.f100,
                    aswt_switch_txn_offline.f101,
                    aswt_switch_txn_offline.f102,
                    aswt_switch_txn_offline.f103,
                    aswt_switch_txn_offline.f104,
                    aswt_switch_txn_offline.f105,
                    aswt_switch_txn_offline.f106,
                    aswt_switch_txn_offline.f107,
                    aswt_switch_txn_offline.f108,
                    aswt_switch_txn_offline.f109,
                    aswt_switch_txn_offline.f110,
                    aswt_switch_txn_offline.f111,
                    aswt_switch_txn_offline.f112,
                    aswt_switch_txn_offline.f113,
                    aswt_switch_txn_offline.f114,
                    aswt_switch_txn_offline.f115,
                    aswt_switch_txn_offline.f116,
                    aswt_switch_txn_offline.f117,
                    aswt_switch_txn_offline.f118,
                    aswt_switch_txn_offline.f119,
                    aswt_switch_txn_offline.f120,
                    aswt_switch_txn_offline.f121,
                    aswt_switch_txn_offline.f122,
                    aswt_switch_txn_offline.f123,
                    aswt_switch_txn_offline.f124,
                    aswt_switch_txn_offline.f125,
                    aswt_switch_txn_offline.f126,
                    aswt_switch_txn_offline.f127,
                    aswt_switch_txn_offline.f128,
                    aswt_switch_txn_offline.reversal_flag,
                    aswt_switch_txn_offline.txn_acquirer,
                    aswt_switch_txn_offline.settle_date,
                    aswt_switch_txn_offline.program_id,
                    aswt_switch_txn_offline.bank_id,
                    aswt_switch_txn_offline.sys_txn_date,
                    aswt_switch_txn_offline.balance_update_flag,
                    aswt_switch_txn_offline.balance_update_date,
                    aswt_switch_txn_offline.sub_batch_no,
                    aswt_switch_txn_offline.acc_flag,
                    aswt_switch_txn_offline.ticket_id,
                    0 AS host_bal,
                    to_number(aswt_switch_txn_offline.chip_balance::text) / 100::numeric AS shadow_bal,
                    aswt_switch_txn_offline.prepaid_account_number
                   FROM aswt_switch_txn_offline
                UNION ALL
                 SELECT aswt_switch_txn_authrization.settle_flag,
                    aswt_switch_txn_authrization.txn_issuer,
                    aswt_switch_txn_authrization.txn_fwd_inst_1,
                    aswt_switch_txn_authrization.txn_fwd_inst_2,
                    aswt_switch_txn_authrization.txn_auth_source,
                    aswt_switch_txn_authrization.txn_channel,
                    aswt_switch_txn_authrization.txn_type,
                    aswt_switch_txn_authrization.txn_code,
                    aswt_switch_txn_authrization.txn_date,
                    aswt_switch_txn_authrization.txn_time,
                    aswt_switch_txn_authrization.fp_masked,
                    aswt_switch_txn_authrization.fp_type,
                    aswt_switch_txn_authrization.int_mti,
                    aswt_switch_txn_authrization.int_ref_no,
                    aswt_switch_txn_authrization.txn_batch_no,
                    aswt_switch_txn_authrization.txn_batch_status,
                    aswt_switch_txn_authrization.drcr,
                    aswt_switch_txn_authrization.fp_form_factor,
                    aswt_switch_txn_authrization.int_seq_no,
                    aswt_switch_txn_authrization.int_rc,
                    aswt_switch_txn_authrization.scheme,
                    aswt_switch_txn_authrization.int_rrn,
                    aswt_switch_txn_authrization.int_proc_code,
                    aswt_switch_txn_authrization.int_amt,
                    aswt_switch_txn_authrization.int_adj_amt1,
                    aswt_switch_txn_authrization.int_adj_amt2,
                    aswt_switch_txn_authrization.int_txn_fees1,
                    aswt_switch_txn_authrization.int_txn_fees2,
                    aswt_switch_txn_authrization.int_pos_entry_mode,
                    aswt_switch_txn_authrization.int_void_flag,
                    aswt_switch_txn_authrization.mti,
                    aswt_switch_txn_authrization.f002,
                    aswt_switch_txn_authrization.f003,
                    aswt_switch_txn_authrization.f004,
                    aswt_switch_txn_authrization.f005,
                    aswt_switch_txn_authrization.f006,
                    aswt_switch_txn_authrization.f007,
                    aswt_switch_txn_authrization.f008,
                    aswt_switch_txn_authrization.f009,
                    aswt_switch_txn_authrization.f010,
                    aswt_switch_txn_authrization.f011,
                    aswt_switch_txn_authrization.f012,
                    aswt_switch_txn_authrization.f013,
                    aswt_switch_txn_authrization.f014,
                    aswt_switch_txn_authrization.f015,
                    aswt_switch_txn_authrization.f016,
                    aswt_switch_txn_authrization.f017,
                    aswt_switch_txn_authrization.f018,
                    aswt_switch_txn_authrization.f019,
                    aswt_switch_txn_authrization.f020,
                    aswt_switch_txn_authrization.f021,
                    aswt_switch_txn_authrization.f022,
                    aswt_switch_txn_authrization.f023,
                    aswt_switch_txn_authrization.f024,
                    aswt_switch_txn_authrization.f025,
                    aswt_switch_txn_authrization.f026,
                    aswt_switch_txn_authrization.f027,
                    aswt_switch_txn_authrization.f028,
                    aswt_switch_txn_authrization.f029,
                    aswt_switch_txn_authrization.f030,
                    aswt_switch_txn_authrization.f031,
                    aswt_switch_txn_authrization.f032,
                    aswt_switch_txn_authrization.f033,
                    aswt_switch_txn_authrization.f034,
                    aswt_switch_txn_authrization.f035,
                    aswt_switch_txn_authrization.f036,
                    aswt_switch_txn_authrization.f037,
                    aswt_switch_txn_authrization.f038,
                    aswt_switch_txn_authrization.f039,
                    aswt_switch_txn_authrization.f040,
                    aswt_switch_txn_authrization.f041,
                    aswt_switch_txn_authrization.f042,
                    aswt_switch_txn_authrization.f043,
                    aswt_switch_txn_authrization.f044,
                    aswt_switch_txn_authrization.f045,
                    aswt_switch_txn_authrization.f046,
                    aswt_switch_txn_authrization.f047,
                    aswt_switch_txn_authrization.f048,
                    aswt_switch_txn_authrization.f049,
                    aswt_switch_txn_authrization.f050,
                    aswt_switch_txn_authrization.f051,
                    aswt_switch_txn_authrization.f052,
                    aswt_switch_txn_authrization.f053,
                    aswt_switch_txn_authrization.f054,
                    aswt_switch_txn_authrization.f055,
                    aswt_switch_txn_authrization.f056,
                    aswt_switch_txn_authrization.f057,
                    aswt_switch_txn_authrization.f058,
                    aswt_switch_txn_authrization.f059,
                    aswt_switch_txn_authrization.f060,
                    aswt_switch_txn_authrization.f061,
                    aswt_switch_txn_authrization.f062,
                    aswt_switch_txn_authrization.f063,
                    aswt_switch_txn_authrization.f064,
                    aswt_switch_txn_authrization.f065,
                    aswt_switch_txn_authrization.f066,
                    aswt_switch_txn_authrization.f067,
                    aswt_switch_txn_authrization.f068,
                    aswt_switch_txn_authrization.f069,
                    aswt_switch_txn_authrization.f070,
                    aswt_switch_txn_authrization.f071,
                    aswt_switch_txn_authrization.f072,
                    aswt_switch_txn_authrization.f073,
                    aswt_switch_txn_authrization.f074,
                    aswt_switch_txn_authrization.f075,
                    aswt_switch_txn_authrization.f076,
                    aswt_switch_txn_authrization.f077,
                    aswt_switch_txn_authrization.f078,
                    aswt_switch_txn_authrization.f079,
                    aswt_switch_txn_authrization.f080,
                    aswt_switch_txn_authrization.f081,
                    aswt_switch_txn_authrization.f082,
                    aswt_switch_txn_authrization.f083,
                    aswt_switch_txn_authrization.f084,
                    aswt_switch_txn_authrization.f085,
                    aswt_switch_txn_authrization.f086,
                    aswt_switch_txn_authrization.f087,
                    aswt_switch_txn_authrization.f088,
                    aswt_switch_txn_authrization.f089,
                    aswt_switch_txn_authrization.f090,
                    aswt_switch_txn_authrization.f091,
                    aswt_switch_txn_authrization.f092,
                    aswt_switch_txn_authrization.f093,
                    aswt_switch_txn_authrization.f094,
                    aswt_switch_txn_authrization.f095,
                    aswt_switch_txn_authrization.f096,
                    aswt_switch_txn_authrization.f097,
                    aswt_switch_txn_authrization.f098,
                    aswt_switch_txn_authrization.f099,
                    aswt_switch_txn_authrization.f100,
                    aswt_switch_txn_authrization.f101,
                    aswt_switch_txn_authrization.f102,
                    aswt_switch_txn_authrization.f103,
                    aswt_switch_txn_authrization.f104,
                    aswt_switch_txn_authrization.f105,
                    aswt_switch_txn_authrization.f106,
                    aswt_switch_txn_authrization.f107,
                    aswt_switch_txn_authrization.f108,
                    aswt_switch_txn_authrization.f109,
                    aswt_switch_txn_authrization.f110,
                    aswt_switch_txn_authrization.f111,
                    aswt_switch_txn_authrization.f112,
                    aswt_switch_txn_authrization.f113,
                    aswt_switch_txn_authrization.f114,
                    aswt_switch_txn_authrization.f115,
                    aswt_switch_txn_authrization.f116,
                    aswt_switch_txn_authrization.f117,
                    aswt_switch_txn_authrization.f118,
                    aswt_switch_txn_authrization.f119,
                    aswt_switch_txn_authrization.f120,
                    aswt_switch_txn_authrization.f121,
                    aswt_switch_txn_authrization.f122,
                    aswt_switch_txn_authrization.f123,
                    aswt_switch_txn_authrization.f124,
                    aswt_switch_txn_authrization.f125,
                    aswt_switch_txn_authrization.f126,
                    aswt_switch_txn_authrization.f127,
                    aswt_switch_txn_authrization.f128,
                    aswt_switch_txn_authrization.reversal_flag,
                    aswt_switch_txn_authrization.txn_acquirer,
                    aswt_switch_txn_authrization.settle_date,
                    aswt_switch_txn_authrization.program_id,
                    aswt_switch_txn_authrization.bank_id,
                    aswt_switch_txn_authrization.sys_txn_date,
                    aswt_switch_txn_authrization.balance_update_flag,
                    aswt_switch_txn_authrization.balance_update_date,
                    aswt_switch_txn_authrization.sub_batch_no,
                    aswt_switch_txn_authrization.acc_flag,
                    NULL::character varying AS ticket_id,
                    aswt_switch_txn_authrization.host_bal,
                    aswt_switch_txn_authrization.shadow_bal,
                    aswt_switch_txn_authrization.prepaid_account_number
                   FROM aswt_switch_txn_authrization
                UNION ALL
                 SELECT digital_txn_authorization.settlement_flag AS settle_flag,
                    ''::character varying AS txn_issuer,
                    ''::character varying AS txn_fwd_inst_1,
                    ''::character varying AS txn_fwd_inst_2,
                    ''::character varying AS txn_auth_source,
                    ''::character varying AS txn_channel,
                    digital_txn_authorization.txn_type,
                    ''::character varying AS txn_code,
                    to_char(digital_txn_authorization.date_time, 'DDMMYYYY'::character varying) AS txn_date,
                    to_char(digital_txn_authorization.date_time, 'hh24miss'::character varying) AS txn_time,
                    ''::character varying AS fp_masked,
                    ''::character varying AS fp_type,
                    ''::character varying AS int_mti,
                    substr(digital_txn_authorization.arn_reference::text, 4::numeric, 16::numeric) AS int_ref_no,
                    ''::character varying AS txn_batch_no,
                    ''::character varying AS txn_batch_status,
                    digital_txn_authorization.dr_cr_flag AS drcr,
                    ''::character varying AS fp_form_factor,
                    ''::character varying AS int_seq_no,
                    ''::character varying AS int_rc,
                    ''::character varying AS scheme,
                    substr(digital_txn_authorization.arn_reference::text, 4::numeric, 16::numeric) AS int_rrn,
                    ''::character varying AS int_proc_code,
                    to_char(lpad((digital_txn_authorization.txn_amount * 100::numeric)::text, 12, 0::text)::character varying) AS int_amt,
                    ''::character varying AS int_adj_amt1,
                    ''::character varying AS int_adj_amt2,
                    ''::character varying AS int_txn_fees1,
                    ''::character varying AS int_txn_fees2,
                    digital_txn_authorization.channel_id AS int_pos_entry_mode,
                    ''::character varying AS int_void_flag,
                    digital_txn_authorization.channel_id AS mti,
                    digital_txn_authorization.card_token AS f002,
                    ''::character varying AS f003,
                    lpad((digital_txn_authorization.txn_amount * 100::numeric)::text, 12, 0::text) AS f004,
                    ''::character varying AS f005,
                    ''::character varying AS f006,
                    ''::character varying AS f007,
                    ''::character varying AS f008,
                    ''::character varying AS f009,
                    ''::character varying AS f010,
                    ''::character varying AS f011,
                    ''::character varying AS f012,
                    ''::character varying AS f013,
                    ''::character varying AS f014,
                    ''::character varying AS f015,
                    ''::character varying AS f016,
                    ''::character varying AS f017,
                    ''::character varying AS f018,
                    ''::character varying AS f019,
                    ''::character varying AS f020,
                    ''::character varying AS f021,
                    ''::character varying AS f022,
                    ''::character varying AS f023,
                    ''::character varying AS f024,
                    ''::character varying AS f025,
                    ''::character varying AS f026,
                    ''::character varying AS f027,
                    ''::character varying AS f028,
                    ''::character varying AS f029,
                    ''::character varying AS f030,
                    ''::character varying AS f031,
                    ''::character varying AS f032,
                    ''::character varying AS f033,
                    ''::character varying AS f034,
                    ''::character varying AS f035,
                    ''::character varying AS f036,
                    substr(digital_txn_authorization.arn_reference::text, 4::numeric, 16::numeric) AS f037,
                    substr(digital_txn_authorization.arn_reference::text, 11::numeric, 16::numeric) AS f038,
                    digital_txn_authorization.response_code AS f039,
                    ''::character varying AS f040,
                    digital_txn_authorization.branch_id AS f041,
                    digital_txn_authorization.mid AS f042,
                    ''::character varying AS f043,
                    ''::character varying AS f044,
                    ''::character varying AS f045,
                    ''::character varying AS f046,
                    ''::character varying AS f047,
                    ''::character varying AS f048,
                    ''::character varying AS f049,
                    ''::character varying AS f050,
                    ''::character varying AS f051,
                    ''::character varying AS f052,
                    ''::character varying AS f053,
                    ''::character varying AS f054,
                    ''::character varying AS f055,
                    ''::character varying AS f056,
                    ''::character varying AS f057,
                    ''::character varying AS f058,
                    ''::character varying AS f059,
                    ''::character varying AS f060,
                    ''::character varying AS f061,
                    ''::character varying AS f062,
                    ''::character varying AS f063,
                    ''::character varying AS f064,
                    ''::character varying AS f065,
                    ''::character varying AS f066,
                    ''::character varying AS f067,
                    ''::character varying AS f068,
                    ''::character varying AS f069,
                    ''::character varying AS f070,
                    ''::character varying AS f071,
                    ''::character varying AS f072,
                    ''::character varying AS f073,
                    ''::character varying AS f074,
                    ''::character varying AS f075,
                    ''::character varying AS f076,
                    ''::character varying AS f077,
                    ''::character varying AS f078,
                    ''::character varying AS f079,
                    ''::character varying AS f080,
                    ''::character varying AS f081,
                    ''::character varying AS f082,
                    ''::character varying AS f083,
                    ''::character varying AS f084,
                    ''::character varying AS f085,
                    ''::character varying AS f086,
                    ''::character varying AS f087,
                    ''::character varying AS f088,
                    ''::character varying AS f089,
                    ''::character varying AS f090,
                    ''::character varying AS f091,
                    ''::character varying AS f092,
                    ''::character varying AS f093,
                    ''::character varying AS f094,
                    ''::character varying AS f095,
                    ''::character varying AS f096,
                    ''::character varying AS f097,
                    ''::character varying AS f098,
                    ''::character varying AS f099,
                    ''::character varying AS f100,
                    ''::character varying AS f101,
                    ''::character varying AS f102,
                    ''::character varying AS f103,
                    ''::character varying AS f104,
                    ''::character varying AS f105,
                    ''::character varying AS f106,
                    ''::character varying AS f107,
                    ''::character varying AS f108,
                    ''::character varying AS f109,
                    ''::character varying AS f110,
                    ''::character varying AS f111,
                    ''::character varying AS f112,
                    ''::character varying AS f113,
                    ''::character varying AS f114,
                    ''::character varying AS f115,
                    ''::character varying AS f116,
                    ''::character varying AS f117,
                    ''::character varying AS f118,
                    ''::character varying AS f119,
                    ''::character varying AS f120,
                    ''::character varying AS f121,
                    ''::character varying AS f122,
                    ''::character varying AS f123,
                    ''::character varying AS f124,
                    ''::character varying AS f125,
                    ''::character varying AS f126,
                    ''::character varying AS f127,
                    ''::character varying AS f128,
                    ''::character varying AS reversal_flag,
                    ''::character varying AS txn_acquirer,
                    digital_txn_authorization.last_settle_date AS settle_date,
                    ''::character varying AS program_id,
                    ''::character varying AS bank_id,
                    digital_txn_authorization.date_time AS sys_txn_date,
                    ''::character varying AS balance_update_flag,
                    NULL::timestamp without time zone AS balance_update_date,
                    0 AS sub_batch_no,
                    NULL::character varying AS acc_flag,
                    NULL::character varying AS ticket_id,
                    digital_txn_authorization.host_bal,
                    digital_txn_authorization.shadow_bal,
                    digital_txn_authorization.prepaid_account_number
                   FROM digital_txn_authorization
        ) UNION
         SELECT ''::character varying AS settle_flag,
            ''::character varying AS txn_issuer,
            ''::character varying AS txn_fwd_inst_1,
            ''::character varying AS txn_fwd_inst_2,
            ''::character varying AS txn_auth_source,
            ''::character varying AS txn_channel,
                CASE
                    WHEN cs_fee_temp.fee_ind::text = 'I'::text THEN '93028'::character varying
                    WHEN cs_fee_temp.fee_ind::text = 'P'::text THEN '93029'::character varying
                    WHEN cs_fee_temp.fee_ind::text = 'R'::text AND cs_fee_temp.fee_description::text = 'REPLOST FOR INSTANT'::text THEN '93128'::character varying
                    WHEN cs_fee_temp.fee_ind::text = 'R'::text AND cs_fee_temp.fee_description::text = 'REPLOST FOR PERSO'::text THEN '93129'::character varying
                    ELSE cs_fee_temp.fee_ind
                END AS txn_type,
            ''::character varying AS txn_code,
            to_char(cs_fee_temp.date_time, 'DDMMYYYY'::character varying) AS txn_date,
            to_char(cs_fee_temp.date_time, 'hh24miss'::character varying) AS txn_time,
            ''::character varying AS fp_masked,
            ''::character varying AS fp_type,
            ''::character varying AS int_mti,
            cs_fee_temp.rrn AS int_ref_no,
            ''::character varying AS txn_batch_no,
            ''::character varying AS txn_batch_status,
            cs_fee_temp.drcr,
            ''::character varying AS fp_form_factor,
            ''::character varying AS int_seq_no,
            ''::character varying AS int_rc,
            ''::character varying AS scheme,
            cs_fee_temp.rrn AS int_rrn,
            ''::character varying AS int_proc_code,
            to_char(lpad((cs_fee_temp.fee_amt * 100::numeric)::text, 12, 0::text)::character varying) AS int_amt,
            ''::character varying AS int_adj_amt1,
            ''::character varying AS int_adj_amt2,
            ''::character varying AS int_txn_fees1,
            ''::character varying AS int_txn_fees2,
            ''::character varying AS int_pos_entry_mode,
            ''::character varying AS int_void_flag,
            ''::character varying AS mti,
            cs_fee_temp.card_number AS f002,
            ''::character varying AS f003,
            lpad((cs_fee_temp.fee_amt * 100::numeric)::text, 12, 0::text) AS f004,
            ''::character varying AS f005,
            ''::character varying AS f006,
            ''::character varying AS f007,
            ''::character varying AS f008,
            ''::character varying AS f009,
            ''::character varying AS f010,
            ''::character varying AS f011,
            ''::character varying AS f012,
            ''::character varying AS f013,
            ''::character varying AS f014,
            ''::character varying AS f015,
            ''::character varying AS f016,
            ''::character varying AS f017,
            ''::character varying AS f018,
            ''::character varying AS f019,
            ''::character varying AS f020,
            ''::character varying AS f021,
            ''::character varying AS f022,
            ''::character varying AS f023,
            ''::character varying AS f024,
            ''::character varying AS f025,
            ''::character varying AS f026,
            ''::character varying AS f027,
            ''::character varying AS f028,
            ''::character varying AS f029,
            ''::character varying AS f030,
            ''::character varying AS f031,
            ''::character varying AS f032,
            ''::character varying AS f033,
            ''::character varying AS f034,
            ''::character varying AS f035,
            ''::character varying AS f036,
            lpad(cs_fee_temp.rrn::text, 12, '0'::text) AS f037,
            lpad(cs_fee_temp.rrn::text, 12, '0'::text) AS f038,
            '00'::character varying AS f039,
            ''::character varying AS f040,
            cs_fee_temp.tid AS f041,
            ( SELECT cms_outlet.parent_id
                   FROM cms_outlet
                  WHERE cms_outlet.outlet_id::text = cs_fee_temp.tid::text) AS f042,
            ''::character varying AS f043,
            ''::character varying AS f044,
            ''::character varying AS f045,
            ''::character varying AS f046,
            ''::character varying AS f047,
            ''::character varying AS f048,
            ''::character varying AS f049,
            ''::character varying AS f050,
            ''::character varying AS f051,
            ''::character varying AS f052,
            ''::character varying AS f053,
            ''::character varying AS f054,
            ''::character varying AS f055,
            ''::character varying AS f056,
            ''::character varying AS f057,
            ''::character varying AS f058,
            ''::character varying AS f059,
            ''::character varying AS f060,
            ''::character varying AS f061,
            ''::character varying AS f062,
            ''::character varying AS f063,
            ''::character varying AS f064,
            ''::character varying AS f065,
            ''::character varying AS f066,
            ''::character varying AS f067,
            ''::character varying AS f068,
            ''::character varying AS f069,
            ''::character varying AS f070,
            ''::character varying AS f071,
            ''::character varying AS f072,
            ''::character varying AS f073,
            ''::character varying AS f074,
            ''::character varying AS f075,
            ''::character varying AS f076,
            ''::character varying AS f077,
            ''::character varying AS f078,
            ''::character varying AS f079,
            ''::character varying AS f080,
            ''::character varying AS f081,
            ''::character varying AS f082,
            ''::character varying AS f083,
            ''::character varying AS f084,
            ''::character varying AS f085,
            ''::character varying AS f086,
            ''::character varying AS f087,
            ''::character varying AS f088,
            ''::character varying AS f089,
            ''::character varying AS f090,
            ''::character varying AS f091,
            ''::character varying AS f092,
            ''::character varying AS f093,
            ''::character varying AS f094,
            ''::character varying AS f095,
            ''::character varying AS f096,
            ''::character varying AS f097,
            ''::character varying AS f098,
            ''::character varying AS f099,
            ''::character varying AS f100,
            ''::character varying AS f101,
            ''::character varying AS f102,
            ''::character varying AS f103,
            ''::character varying AS f104,
            ''::character varying AS f105,
            ''::character varying AS f106,
            ''::character varying AS f107,
            ''::character varying AS f108,
            ''::character varying AS f109,
            ''::character varying AS f110,
            ''::character varying AS f111,
            ''::character varying AS f112,
            ''::character varying AS f113,
            ''::character varying AS f114,
            ''::character varying AS f115,
            ''::character varying AS f116,
            ''::character varying AS f117,
            ''::character varying AS f118,
            ''::character varying AS f119,
            ''::character varying AS f120,
            ''::character varying AS f121,
            ''::character varying AS f122,
            ''::character varying AS f123,
            ''::character varying AS f124,
            ''::character varying AS f125,
            ''::character varying AS f126,
            ''::character varying AS f127,
            ''::character varying AS f128,
            ''::character varying AS reversal_flag,
            ''::character varying AS txn_acquirer,
            cs_fee_temp.date_time AS settle_date,
            ''::character varying AS program_id,
            ''::character varying AS bank_id,
            cs_fee_temp.date_time AS sys_txn_date,
            ''::character varying AS balance_update_flag,
            NULL::timestamp without time zone AS balance_update_date,
            0 AS sub_batch_no,
            NULL::character varying AS acc_flag,
            NULL::character varying AS ticket_id,
            cs_fee_temp.host_bal,
            cs_fee_temp.shadow_bal,
            cs_fee_temp.prepaid_account_number
           FROM cs_fee_temp
) UNION ALL
 SELECT ''::character varying AS settle_flag,
    ''::character varying AS txn_issuer,
    ''::character varying AS txn_fwd_inst_1,
    ''::character varying AS txn_fwd_inst_2,
    ''::character varying AS txn_auth_source,
    ''::character varying AS txn_channel,
    cs_manual_adjustment.txn_type,
    ''::character varying AS txn_code,
    to_char(cs_manual_adjustment.transaction_date, 'DDMMYYYY'::character varying) AS txn_date,
    cs_manual_adjustment.transaction_time AS txn_time,
    ''::character varying AS fp_masked,
    ''::character varying AS fp_type,
    ''::character varying AS int_mti,
    cs_manual_adjustment.rrn AS int_ref_no,
    ''::character varying AS txn_batch_no,
    ''::character varying AS txn_batch_status,
    cs_manual_adjustment.dr_cr_ind AS drcr,
    ''::character varying AS fp_form_factor,
    ''::character varying AS int_seq_no,
    ''::character varying AS int_rc,
    ''::character varying AS scheme,
    cs_manual_adjustment.rrn AS int_rrn,
    ''::character varying AS int_proc_code,
    to_char(lpad((cs_manual_adjustment.amount * 100::numeric)::text, 12, 0::text)::character varying) AS int_amt,
    ''::character varying AS int_adj_amt1,
    ''::character varying AS int_adj_amt2,
    ''::character varying AS int_txn_fees1,
    ''::character varying AS int_txn_fees2,
    ''::character varying AS int_pos_entry_mode,
    ''::character varying AS int_void_flag,
    ''::character varying AS mti,
    cs_manual_adjustment.card_number AS f002,
    ''::character varying AS f003,
    lpad((cs_manual_adjustment.amount * 100::numeric)::text, 12, 0::text) AS f004,
    ''::character varying AS f005,
    ''::character varying AS f006,
    ''::character varying AS f007,
    ''::character varying AS f008,
    ''::character varying AS f009,
    ''::character varying AS f010,
    ''::character varying AS f011,
    ''::character varying AS f012,
    ''::character varying AS f013,
    ''::character varying AS f014,
    ''::character varying AS f015,
    ''::character varying AS f016,
    ''::character varying AS f017,
    ''::character varying AS f018,
    ''::character varying AS f019,
    ''::character varying AS f020,
    ''::character varying AS f021,
    ''::character varying AS f022,
    ''::character varying AS f023,
    ''::character varying AS f024,
    ''::character varying AS f025,
    ''::character varying AS f026,
    ''::character varying AS f027,
    ''::character varying AS f028,
    ''::character varying AS f029,
    ''::character varying AS f030,
    ''::character varying AS f031,
    ''::character varying AS f032,
    ''::character varying AS f033,
    ''::character varying AS f034,
    ''::character varying AS f035,
    ''::character varying AS f036,
    cs_manual_adjustment.rrn AS f037,
    cs_manual_adjustment.approval_code AS f038,
    '00'::character varying AS f039,
    ''::character varying AS f040,
    cs_manual_adjustment.tid AS f041,
    ( SELECT cms_outlet.parent_id
           FROM cms_outlet
          WHERE cms_outlet.outlet_id::text = cs_manual_adjustment.tid::text) AS f042,
    ''::character varying AS f043,
    ''::character varying AS f044,
    ''::character varying AS f045,
    ''::character varying AS f046,
    ''::character varying AS f047,
    ''::character varying AS f048,
    ''::character varying AS f049,
    ''::character varying AS f050,
    ''::character varying AS f051,
    ''::character varying AS f052,
    ''::character varying AS f053,
    ''::character varying AS f054,
    ''::character varying AS f055,
    ''::character varying AS f056,
    ''::character varying AS f057,
    ''::character varying AS f058,
    ''::character varying AS f059,
    ''::character varying AS f060,
    ''::character varying AS f061,
    ''::character varying AS f062,
    ''::character varying AS f063,
    ''::character varying AS f064,
    ''::character varying AS f065,
    ''::character varying AS f066,
    ''::character varying AS f067,
    ''::character varying AS f068,
    ''::character varying AS f069,
    ''::character varying AS f070,
    ''::character varying AS f071,
    ''::character varying AS f072,
    ''::character varying AS f073,
    ''::character varying AS f074,
    ''::character varying AS f075,
    ''::character varying AS f076,
    ''::character varying AS f077,
    ''::character varying AS f078,
    ''::character varying AS f079,
    ''::character varying AS f080,
    ''::character varying AS f081,
    ''::character varying AS f082,
    ''::character varying AS f083,
    ''::character varying AS f084,
    ''::character varying AS f085,
    ''::character varying AS f086,
    ''::character varying AS f087,
    ''::character varying AS f088,
    ''::character varying AS f089,
    ''::character varying AS f090,
    ''::character varying AS f091,
    ''::character varying AS f092,
    ''::character varying AS f093,
    ''::character varying AS f094,
    ''::character varying AS f095,
    ''::character varying AS f096,
    ''::character varying AS f097,
    ''::character varying AS f098,
    ''::character varying AS f099,
    ''::character varying AS f100,
    ''::character varying AS f101,
    ''::character varying AS f102,
    ''::character varying AS f103,
    ''::character varying AS f104,
    ''::character varying AS f105,
    ''::character varying AS f106,
    ''::character varying AS f107,
    ''::character varying AS f108,
    ''::character varying AS f109,
    ''::character varying AS f110,
    ''::character varying AS f111,
    ''::character varying AS f112,
    ''::character varying AS f113,
    ''::character varying AS f114,
    ''::character varying AS f115,
    ''::character varying AS f116,
    ''::character varying AS f117,
    ''::character varying AS f118,
    ''::character varying AS f119,
    ''::character varying AS f120,
    ''::character varying AS f121,
    ''::character varying AS f122,
    ''::character varying AS f123,
    ''::character varying AS f124,
    ''::character varying AS f125,
    ''::character varying AS f126,
    ''::character varying AS f127,
    ''::character varying AS f128,
    ''::character varying AS reversal_flag,
    ''::character varying AS txn_acquirer,
    cs_manual_adjustment.action_date AS settle_date,
    ''::character varying AS program_id,
    ''::character varying AS bank_id,
    cs_manual_adjustment.action_date AS sys_txn_date,
    ''::character varying AS balance_update_flag,
    NULL::timestamp without time zone AS balance_update_date,
    0 AS sub_batch_no,
    NULL::character varying AS acc_flag,
    NULL::character varying AS ticket_id,
    cs_manual_adjustment.host_bal,
    cs_manual_adjustment.shadow_bal,
    cs_manual_adjustment.prepaid_account_number
   FROM cs_manual_adjustment
  ORDER BY 164 DESC;


-- last_action_on_card source

CREATE OR REPLACE VIEW last_action_on_card
AS SELECT rownum AS row_num,
    __unnamed_subquery_0.status_flag,
    __unnamed_subquery_0.insert_time,
    __unnamed_subquery_0.card_ref_number,
    __unnamed_subquery_0.source_type
   FROM ( SELECT his.status_flag,
            his.insert_time,
            his.old_card_ref_number AS card_ref_number,
            his.source_type
           FROM card_detail cd
             JOIN cms_card_detail_history his ON cd.hash_card_number::text = his.old_pan::text
          ORDER BY his.insert_time DESC) __unnamed_subquery_0;


-- menus source

CREATE OR REPLACE VIEW menus
AS SELECT pm.id AS page_id,
    pm.page_name,
    pm.page_link,
    rpl.role_id,
    pm.display_order
   FROM page_master pm,
    role_page_link rpl
  WHERE pm.parent_page_id = 0::numeric AND pm.grand_parent_page_id = 0::numeric AND rpl.page_id = pm.id AND pm.status::text = 'A'::text;


-- submenus source

CREATE OR REPLACE VIEW submenus
AS SELECT pm.id AS page_id,
    pm.page_name,
    pm.page_link,
    rpl.role_id,
    pm.display_order,
    pm.parent_page_id AS menu_id
   FROM page_master pm,
    role_page_link rpl
  WHERE pm.grand_parent_page_id = 0::numeric AND pm.parent_page_id <> 0::numeric AND rpl.page_id = pm.id AND pm.status::text = 'A'::text;


-- subsubmenus source

CREATE OR REPLACE VIEW subsubmenus
AS SELECT pm.id AS page_id,
    pm.page_name,
    pm.page_link,
    rpl.role_id,
    pm.display_order,
    pm.grand_parent_page_id AS menu_id,
    pm.parent_page_id AS submenu_id
   FROM page_master pm,
    role_page_link rpl
  WHERE pm.grand_parent_page_id <> 0::numeric AND pm.parent_page_id <> 0::numeric AND rpl.page_id = pm.id AND pm.status::text = 'A'::text;


-- top_up_view source

CREATE OR REPLACE VIEW top_up_view
AS SELECT a.card_enc AS card_no,
    a.txn_amount AS amount,
    a.date_time AS txn_time
   FROM digital_txn_authorization a
  WHERE a.txn_type::text = 21028::text
UNION
 SELECT b.f002 AS card_no,
    b.f004::numeric / 100::numeric AS amount,
    b.sys_txn_date AS txn_time
   FROM aswt_switch_txn_authrization b
  WHERE b.txn_type::text = 21028::text AND b.f039::text = '00'::text AND b.drcr::text = 'C'::text;
